import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author silva
 */
public class CadServico extends javax.swing.JFrame {

    /**
     * Creates new form CadServico
     */
    public CadServico() {
        initComponents();
        Color cor = new Color(33,44,52);
        getContentPane().setBackground(cor);
            try{
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection conexao = DriverManager.getConnection("jdbc:mysql://localhost:3306/tech_service",
                                                            "root","");
        
    //comando sql
        PreparedStatement st =conexao.prepareStatement("select nome from funcionario where cargo = 'Tecnico'");
                                                         
      
        ResultSet retorno = st.executeQuery();//executa o comando select

        while(retorno.next()){
         cmbResp.addItem(retorno.getString("nome"));
        }
    }catch (ClassNotFoundException ex){
        JOptionPane.showMessageDialog(null,"Driver não colocado corretamente no library");
    }catch (SQLException ex){
        JOptionPane.showMessageDialog(null, "Verifique os parâmetros de conexão com o banco de dados" + ex.getMessage());
    }    

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnCadServico = new javax.swing.JButton();
        txtTipoServico = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        txtAparelho = new javax.swing.JTextField();
        txtDocumento = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDefeito = new javax.swing.JEditorPane();
        cmbResp = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Serviço");
        setName(""); // NOI18N
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(194, 190, 190));
        jLabel1.setText("Responsável");
        jLabel1.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jLabel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jLabel1.setName(""); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(0, 0));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(390, 100, 110, 20);

        jLabel2.setBackground(new java.awt.Color(0, 204, 153));
        jLabel2.setForeground(new java.awt.Color(194, 190, 190));
        jLabel2.setText("Tipo do Serviço");
        jLabel2.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jLabel2.setMinimumSize(new java.awt.Dimension(0, 0));
        jLabel2.setName(""); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(0, 0));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 10, 110, 20);

        jLabel3.setForeground(new java.awt.Color(194, 190, 190));
        jLabel3.setText("Valor");
        jLabel3.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jLabel3.setMinimumSize(new java.awt.Dimension(0, 0));
        jLabel3.setName(""); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(0, 0));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 50, 110, 20);

        jLabel4.setForeground(new java.awt.Color(194, 190, 190));
        jLabel4.setText("Defeito Informado");
        jLabel4.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jLabel4.setMinimumSize(new java.awt.Dimension(0, 0));
        jLabel4.setName(""); // NOI18N
        jLabel4.setPreferredSize(new java.awt.Dimension(0, 0));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 90, 110, 20);

        jLabel5.setForeground(new java.awt.Color(194, 190, 190));
        jLabel5.setText("Aparelho");
        jLabel5.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jLabel5.setMinimumSize(new java.awt.Dimension(0, 0));
        jLabel5.setName(""); // NOI18N
        jLabel5.setPreferredSize(new java.awt.Dimension(0, 0));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(390, 10, 110, 20);

        jLabel6.setForeground(new java.awt.Color(194, 190, 190));
        jLabel6.setText("Documento Cliente");
        jLabel6.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jLabel6.setMinimumSize(new java.awt.Dimension(0, 0));
        jLabel6.setName(""); // NOI18N
        jLabel6.setPreferredSize(new java.awt.Dimension(0, 0));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(390, 50, 110, 20);

        btnCadServico.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCadServico.setText("Cadastrar Serviço");
        btnCadServico.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        btnCadServico.setMinimumSize(new java.awt.Dimension(0, 0));
        btnCadServico.setName(""); // NOI18N
        btnCadServico.setPreferredSize(new java.awt.Dimension(0, 0));
        btnCadServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadServicoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadServico);
        btnCadServico.setBounds(320, 240, 160, 30);

        txtTipoServico.setMinimumSize(new java.awt.Dimension(0, 0));
        txtTipoServico.setName(""); // NOI18N
        txtTipoServico.setPreferredSize(new java.awt.Dimension(0, 0));
        txtTipoServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoServicoActionPerformed(evt);
            }
        });
        getContentPane().add(txtTipoServico);
        txtTipoServico.setBounds(120, 10, 200, 30);

        txtValor.setMinimumSize(new java.awt.Dimension(0, 0));
        txtValor.setName(""); // NOI18N
        txtValor.setPreferredSize(new java.awt.Dimension(0, 0));
        txtValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorActionPerformed(evt);
            }
        });
        getContentPane().add(txtValor);
        txtValor.setBounds(120, 50, 200, 30);

        txtAparelho.setMinimumSize(new java.awt.Dimension(0, 0));
        txtAparelho.setName(""); // NOI18N
        txtAparelho.setPreferredSize(new java.awt.Dimension(0, 0));
        getContentPane().add(txtAparelho);
        txtAparelho.setBounds(500, 10, 200, 30);

        txtDocumento.setMinimumSize(new java.awt.Dimension(0, 0));
        txtDocumento.setName(""); // NOI18N
        txtDocumento.setPreferredSize(new java.awt.Dimension(0, 0));
        getContentPane().add(txtDocumento);
        txtDocumento.setBounds(500, 50, 200, 30);

        jScrollPane1.setViewportView(txtDefeito);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(120, 90, 240, 100);

        cmbResp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRespActionPerformed(evt);
            }
        });
        getContentPane().add(cmbResp);
        cmbResp.setBounds(500, 90, 200, 40);

        setSize(new java.awt.Dimension(881, 374));
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void btnCadServicoActionPerformed(java.awt.event.ActionEvent evt) {                                              
           String ts, v,di,ap,dc,r;
            ts = txtTipoServico.getText();
            v = txtValor.getText();
            di = txtDefeito.getText();
            ap = txtAparelho.getText();
            dc= txtDocumento.getText();
            r = cmbResp.getSelectedItem().toString();
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conexao = DriverManager.getConnection("jdbc:mysql://localhost:3306/tech_service",
                                                            "root","");
         
          
        //Enviando os dados
            PreparedStatement st = conexao.prepareStatement("insert into servico(tipo_servico, valor_servico,"
                    + "defeito_informado,aparelho,doc_cliente,funcionario_responsavel) values(?,?,?,?,?,?)");
            st.setString(1,ts);
            st.setString(2,v);
            st.setString(3,di);
            st.setString(4,ap);
            st.setString(5,dc);
            st.setString(6,r);
            st.executeUpdate();
                JOptionPane.showMessageDialog(null,"Serviço Cadastrado com sucesso");
           
       
        
            //executando o insert
        
            txtTipoServico.setText("");
            txtValor.setText("");
           txtAparelho.setText("");
            txtDefeito.setText("");
            txtDocumento.setText("");
            
            txtTipoServico.requestFocus();
        }catch (ClassNotFoundException ex){
             JOptionPane.showMessageDialog(null,"Driver não colocado corretamente no library");
        }catch (SQLException ex){
            JOptionPane.showMessageDialog(null, "Verifique os parâmetros de conexão com o banco de dados" + ex.getMessage());
    }
    }                                             

    private void txtValorActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void txtTipoServicoActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void cmbRespActionPerformed(java.awt.event.ActionEvent evt) {                                        
   
    }                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadServico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnCadServico;
    private javax.swing.JComboBox<String> cmbResp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAparelho;
    private javax.swing.JEditorPane txtDefeito;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtTipoServico;
    private javax.swing.JTextField txtValor;
    // End of variables declaration                   
}
