
import Classes.CpfCliente;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author matheus.silva
 */
public class MenuRecepcao extends javax.swing.JFrame {

    /**
     * Creates new form MenuRecepcao
     */
    public MenuRecepcao() {
        initComponents();
        Color cor = new Color(33, 44, 52);
        getContentPane().setBackground(cor);
        //this.setIconImage(new javax.swing.I
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itmConsultar = new javax.swing.JMenuItem();
        itmCadCliente = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itmConsultarServico = new javax.swing.JMenuItem();
        itmCadServico = new javax.swing.JMenuItem();
        itmExcluir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo hp.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 10, 270, 230);

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 204));
        jMenuBar1.setAutoscrolls(true);
        jMenuBar1.setOpaque(true);

        jMenu1.setText("Clientes");

        itmConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/person_search_1.png"))); // NOI18N
        itmConsultar.setText("Consultar");
        itmConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmConsultarActionPerformed(evt);
            }
        });
        jMenu1.add(itmConsultar);

        itmCadCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cad cliente.png"))); // NOI18N
        itmCadCliente.setText("Cadastrar");
        itmCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCadClienteActionPerformed(evt);
            }
        });
        jMenu1.add(itmCadCliente);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Serviços");

        itmConsultarServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/quick_reference_all.png"))); // NOI18N
        itmConsultarServico.setText("Consultar");
        itmConsultarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmConsultarServicoActionPerformed(evt);
            }
        });
        jMenu2.add(itmConsultarServico);

        itmCadServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Categoria.png"))); // NOI18N
        itmCadServico.setText("Cadastrar");
        itmCadServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCadServicoActionPerformed(evt);
            }
        });
        jMenu2.add(itmCadServico);

        itmExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/excluir.png"))); // NOI18N
        itmExcluir.setText("Excluir");
        itmExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExcluirActionPerformed(evt);
            }
        });
        jMenu2.add(itmExcluir);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(698, 322));
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void itmConsultarActionPerformed(java.awt.event.ActionEvent evt) {                                             
        String c;
        c = JOptionPane.showInputDialog("Digite o CPF do cliente");
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conexao = DriverManager.getConnection("jdbc:mysql://localhost:3306/tech_service",
                    "root", "");
            //Buscando o cliente
            PreparedStatement st = conexao.prepareStatement("select * from cliente where documento = ?");
            st.setString(1, c);
            ResultSet resultado = st.executeQuery(); //executa o select
            if (!resultado.isBeforeFirst()) {
                JOptionPane.showMessageDialog(null, "Cliente não Cadastrado");
            } else {
                JOptionPane.showMessageDialog(null, "Cliente já Cadastrado");
            }
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Driver não colocado na library");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro nos dados do banco de dados " + ex.getMessage());
        }
    }                                            

    private void itmCadClienteActionPerformed(java.awt.event.ActionEvent evt) {                                              
        new CadastroCliente().setVisible(true);
    }                                             

    private void itmCadServicoActionPerformed(java.awt.event.ActionEvent evt) {                                              
        new CadServico().setVisible(true);
    }                                             

    private void itmConsultarServicoActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        new ConsultaServico().setVisible(true);
    }                                                   

    private void itmExcluirActionPerformed(java.awt.event.ActionEvent evt) {                                           
        String d;
        d = JOptionPane.showInputDialog(null, "Digite o número da ordem de serviço a ser exlcuída");
        int y = JOptionPane.showConfirmDialog(null, "Tem Certeza?");
        if (y == 1 || y == 2) {
            return;
        }
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conexao = DriverManager.getConnection("jdbc:mysql://localhost:3306/tech_service",
                    "root", "");
            //Enviando os dados
            PreparedStatement st = conexao.prepareStatement("delete from servico where id_servico = ?");
            st.setString(1, d);

            int result = st.executeUpdate();//executando o insert
            if (result == 1) {
                JOptionPane.showMessageDialog(null, "Serviço excluido com sucesso");

            } else {
                JOptionPane.showMessageDialog(null, "Serviço não encontrado");
            }

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Driver não colocado corretamente no library");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Verifique os parâmetros de conexão com o banco de dados" + ex.getMessage());
        }
    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuRecepcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuRecepcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuRecepcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuRecepcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuRecepcao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JMenuItem itmCadCliente;
    private javax.swing.JMenuItem itmCadServico;
    private javax.swing.JMenuItem itmConsultar;
    private javax.swing.JMenuItem itmConsultarServico;
    private javax.swing.JMenuItem itmExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration                   
}
