import Classes.CpfCliente;
import java.awt.Color;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author silva
 */
public class TelaCli extends javax.swing.JFrame {

    /**
     * Creates new form TelaCli
     */
    public TelaCli() {
        initComponents();
        Color cor = new Color(33,44,52);
        getContentPane().setBackground(cor);
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCpf = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        btnVoltar2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela cliente");
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(130, 151, 240));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(194, 190, 190));
        jLabel1.setText("Insira seu CPF para visualizar seus serviços");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 50, 320, 38);

        txtCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfActionPerformed(evt);
            }
        });
        getContentPane().add(txtCpf);
        txtCpf.setBounds(140, 100, 203, 38);

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar);
        btnConsultar.setBounds(180, 170, 121, 23);

        btnVoltar2.setBackground(new java.awt.Color(151, 180, 210));
        btnVoltar2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        btnVoltar2.setText("Voltar");
        btnVoltar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltar2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar2);
        btnVoltar2.setBounds(6, 6, 60, 20);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo_hp_menor.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(200, 0, 80, 60);

        setSize(new java.awt.Dimension(479, 290));
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void txtCpfActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {                                             
        String cpf = txtCpf.getText();
        CpfCliente.setCpfCli(cpf);
        txtCpf.setText("");
        
        new OsCliente().setVisible(true);
    }                                            

    private void btnVoltar2ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        new TelaInicial().setVisible(true);
    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCli().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnVoltar2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtCpf;
    // End of variables declaration                   
}
