import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.JFrame;
import javax.swing.SwingConstants;
import java.awt.*;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author silva
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
        Color cor = new Color(33,44,52);
        getContentPane().setBackground(cor);
       //this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo hp.png")).getImage());
        setExtendedState(MAXIMIZED_BOTH);
        lbLogo.setHorizontalAlignment(SwingConstants.CENTER);
        
        
        lbPergunta.setHorizontalAlignment(SwingConstants.CENTER);
        
        
        
        addComponentListener(new ComponentAdapter(){
            public void componentResized(ComponentEvent e){
                atualizarComponentes();
            }
        });
    }
    private void atualizarComponentes(){
        int larguraJanela = getWidth();
        int larguraLabel = 300;
        int xLabel = (larguraJanela - larguraLabel)/2;
         lbLogo.setBounds(xLabel, 10, larguraLabel, 210);
        lbPergunta.setBounds(xLabel, 230,larguraLabel, 40);
        cmbPerfil.setBounds(xLabel, 280, larguraLabel, 40);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        lbPergunta = new javax.swing.JLabel();
        cmbPerfil = new javax.swing.JComboBox<>();
        lbLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Inicial");
        setBackground(new java.awt.Color(51, 68, 82));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(204, 204, 204));
        setMaximumSize(null);
        getContentPane().setLayout(null);

        lbPergunta.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lbPergunta.setForeground(new java.awt.Color(194, 190, 190));
        lbPergunta.setText("Se Identifique");
        lbPergunta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbPergunta.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(lbPergunta);
        lbPergunta.setBounds(90, 280, 220, 70);

        cmbPerfil.setBackground(new java.awt.Color(34, 126, 181));
        cmbPerfil.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbPerfil.setForeground(new java.awt.Color(255, 255, 255));
        cmbPerfil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Cliente", "Funcionário" }));
        cmbPerfil.setBorder(null);
        cmbPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cmbPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPerfilActionPerformed(evt);
            }
        });
        getContentPane().add(cmbPerfil);
        cmbPerfil.setBounds(90, 380, 250, 30);

        lbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo hp.png"))); // NOI18N
        getContentPane().add(lbLogo);
        lbLogo.setBounds(90, 10, 280, 210);

        setSize(new java.awt.Dimension(521, 440));
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void cmbPerfilActionPerformed(java.awt.event.ActionEvent evt) {                                          
      String perfil = cmbPerfil.getSelectedItem().toString();
      String func = "Funcionário";
      String clie = "Cliente";
      
      if(perfil.equals(func)){
          new LoginFunc().setVisible(true);
      } else if(perfil.equals(clie)){
          new TelaCli().setVisible(true); 
      }else{
          JOptionPane.showMessageDialog(null, "Opção inválida. Escolha entre 'Cliente' ou 'Funcionário'");    
      }
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JComboBox<String> cmbPerfil;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lbPergunta;
    // End of variables declaration                   

    private void setIconImage() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
