
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import Classes.NomeFunc;
import java.awt.Color;
import javax.swing.SwingConstants;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author silva
 */
public class LoginFunc extends javax.swing.JFrame {

    /**
     * Creates new form LoginFunc
     */
    public LoginFunc() {
        initComponents();
       Color cor = new Color(33,44,52);
        getContentPane().setBackground(cor);
        //this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo hp.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        pLogin = new javax.swing.JPanel();
        txtUser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        btnEntar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");
        getContentPane().setLayout(null);

        pLogin.setBackground(new java.awt.Color(88, 194, 114));
        pLogin.setLayout(null);

        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });
        pLogin.add(txtUser);
        txtUser.setBounds(70, 69, 137, 31);

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setText("Usuário");
        pLogin.add(jLabel2);
        jLabel2.setBounds(6, 48, 58, 28);

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Login");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(6, 0, 93, 30);

        pLogin.add(jPanel2);
        jPanel2.setBounds(0, 0, 260, 0);
        pLogin.add(txtSenha);
        txtSenha.setBounds(70, 139, 137, 31);

        btnEntar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEntar.setForeground(new java.awt.Color(0, 207, 27));
        btnEntar.setText("Entrar");
        btnEntar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntarActionPerformed(evt);
            }
        });
        pLogin.add(btnEntar);
        btnEntar.setBounds(92, 188, 72, 23);

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel3.setText("Senha");
        pLogin.add(jLabel3);
        jLabel3.setBounds(12, 129, 52, 28);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo_hp_menor.png"))); // NOI18N
        pLogin.add(jLabel4);
        jLabel4.setBounds(90, 0, 80, 70);

        getContentPane().add(pLogin);
        pLogin.setBounds(138, 50, 260, 230);

        btnVoltar.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar);
        btnVoltar.setBounds(10, 10, 70, 20);

        setSize(new java.awt.Dimension(550, 345));
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        new TelaInicial().setVisible(true);
    }                                         

    private void btnEntarActionPerformed(java.awt.event.ActionEvent evt) {                                         
      String u, s;
       u = txtUser.getText();
       s = txtSenha.getText();
       
     try{
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection conexao = DriverManager.getConnection("jdbc:mysql://localhost:3306/tech_service",
                                                            "root","");
        
    //comando sql
        PreparedStatement st =conexao.prepareStatement("select nome, login, senha, cargo from funcionario where login = ? and senha = ? ");
        st.setString(1,u);
        st.setString(2, s);
       ResultSet usuario = st.executeQuery();//executando o comando
       
       if(usuario.next()){
           String nome = usuario.getString("nome");
           NomeFunc.setNomeF(nome);
           String cargo = usuario.getString("cargo");
           if(cargo.equals("Tecnico")){
              new MenuTecnico().setVisible(true); 
           }else{
               new MenuRecepcao().setVisible(true);
           }
          // new MenuTecnico().setVisible(true);
      
       } else{
           JOptionPane.showMessageDialog(null, "Usuário e/ou Senha inválidos");
       }
          
    }catch (ClassNotFoundException ex){
        JOptionPane.showMessageDialog(null,"Driver não colocado corretamente no library");
    }catch (SQLException ex){
        JOptionPane.showMessageDialog(null, "Verifique os parâmetros de conexão com o banco de dados" + ex.getMessage());
    }
        dispose();
        
        
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFunc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnEntar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pLogin;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUser;
    // End of variables declaration                   
}
